---
title: "Economic Connectedness"
format: html
author: Luke Li
execute:
    echo: false
---

```{r}
#| message: false
#| warning: false
library(tidyverse)
library(primer.data)
```

## GRAPH 1

```{r}
#| message: false
connectedness |>
  drop_na() |>
  ggplot(aes(x = population)) + 
    geom_histogram(bins = 100, fill = "black", color = "white") + 
    scale_x_log10(labels = scales::comma_format()) +
    labs(title = "US County Popoulation Distribution 2018", 
  subtitle = "Popoulations are heavily skewed right, x-axis uses log scale", 
  x = "County Population", 
  y = "Number of Counties",
  caption = "Opportunity Insights")
```

## GRAPH 2

```{r}
#| message: false
connectedness |>
    drop_na() |> 
    ggplot(aes(x = population, y = connectedness)) + 
    geom_point(alpha = 0.3, fill = "black", color = "black", stroke = 0, size = 3) + 
    geom_smooth(method = "lm", se = FALSE, color = "red") + 
    scale_x_log10(label = scales::comma) +
    labs(title = "US County Populations verses Economic Connectedness 2018", subtitle = "Population size does not matter to EC", caption = "Opportunity Insights", x = "Population", y = "Economic Connectedness")
```
